export const GET_ERRORS = 'GET_ERRORS';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_UPDATE = "USER_UPDATE";
export const USER_DELETE = "USER_DELETE";

export const CREATE_CART = 'CREATE_CART';
export const DELETE_CART = 'REMOVE_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const SAVED_PRODUCT_IN_CART = 'SAVED_PRODUCT_IN_CART';
export const CART_ERROR = "CART_ERROR";
export const LOADED_CART = "LOADED_CART";
export const LOADING_CART = "LOADING_CART";

export const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
export const LOADED_PRODUCTS = "LOADED_PRODUCTS";
export const PRODUCT_ERROR = "PRODUCT_ERROR";


